#!/bin/bash

## xterm options:

font='-dec-terminal-bold-r-normal--14-0-75-75-c-*-dec-dectech' 
font='-dec-terminal-bold-r-normal-*-14-*-*-*-*-*-dec-dectech'
font="fixed"

geom=%80x25

hold="-hold"
hold=""


## lse options/environment:

# export LC_ALL=en_US.UTF-8

# export LSE_OUTPUT_ARROWS=ASCII
# export LSE_OUTPUT_ARROWS=DECTECH
# export LSE_OUTPUT_ARROWS=UNICODE
export LSE_OUTPUT_ARROWS=UNICODE-HAFLWIDTH

export LSE_RETURN_IS_XOFF=T
# export LSE_RETURN_IS_XOFF=NIL

# export LSE_REJECT_LOWCASE_INPUT=T
export LSE_REJECT_LOWCASE_INPUT=NIL

export LSE_UPCASE_OUTPUT=T
# export LSE_UPCASE_OUTPUT=NIL

export LSE_ACCENTED_OUTPUT=NIL
# export LSE_ACCENTED_OUTPUT=T

# export LSE_NO_BELL=T
export LSE_NO_BELL=NIL

# export LSE_MODERN_MODE=T
export LSE_MODERN_MODE=NIL

# export LSE_PAGER=NIL
export LSE_PAGER=T
# export LSE_PAGER=25



lse="lse"
bin="$(dirname $0)/.."
second=0

for arg ; do
    case "$arg" in
    --second)
        second=1
        ;;
    *)
        lse="$arg"
        ;;
    esac
done

if [ "$second" -ne 0 ] ; then
    save="`stty --save`"
    trap "echo '' ; echo Exiting... ; stty \"$save\" ; exit " SIGINT SIGTERM SIGQUIT

    # We reset the terminal to function as a LSE console.
    # The intr signal is sent upon CTRL-A  key (used by ATT() function).
    # The quit signal is sent upon ESC key key.
    # Start, stop and susp signals are not mapped.
    stty raw  \
        olcuc -ocrnl -onlcr \
        -echo -echoe -echok -echonl -echoprt -echoke -echoctl \
        intr   0x01 \
        start  0x00 \
        stop   0x00 \
        susp   0x00 \
        quit   0x1b \
        erase  0x00 \
        kill   0x00 \
        eof    0x00 \
        eol    0x00 \
        eol2   0x00 \
        rprnt  0x00 \
        werase 0x00 \
        lnext  0x00 

    "$lse" 2> /tmp/lse.trace

    stty "$save"
else

    xterm \
        ${geom} \
        -bg '#000' \
        -fg '#5f2' \
        -fn "$font" \
        -T 'L.S.E. - Console no. 0' \
        +mb +vb +aw +rw -dc \
        ${hold} \
        -e "$0" --second "$bin/lse" \
        &

fi

exit 0
#### THE END ####
