#!/bin/bash
SERVER_DIR=/srv/lse
ROOT=${SERVER_DIR}/files
exec shellinaboxd \
     --background=/var/run/lse.pid \
     --port=8117 \
     --disable-ssl \
     --user=lse \
     --group=lse \
     --css="${SERVER_DIR}/scripts/style.css" \
     --service="/:lse:lse:${ROOT}:${SERVER_DIR}/scripts/lse-siab.sh ${peer}"
# ---
     --verbose \
