;;; This file was generated by Zebu (Version 3.5.5)

(IN-PACKAGE "COM.INFORMATIMAGO.LSE")
(REQUIRE "zebu-package")
(USE-PACKAGE "ZEBU")


(DEFUN EXECUTER/111 (TOK-EXECUTER EXPRESSION)
  (DECLARE (IGNORE TOK-EXECUTER))
  (LIST :EXECUTER EXPRESSION))

(DEFUN EXECUTER11 (EXECUTER/1 TOK-VIRGULE EXPRESSION)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC EXECUTER/1 EXPRESSION))

(DEFUN SUPPRIMER/111 (TOK-SUPPRIMER EXPRESSION)
  (DECLARE (IGNORE TOK-SUPPRIMER))
  (LIST :SUPPRIMER EXPRESSION))

(DEFUN SUPPRIMER11 (SUPPRIMER/1 TOK-VIRGULE EXPRESSION)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC SUPPRIMER/1 EXPRESSION))

(DEFUN CHARGER/111 (TOK-CHARGER IDENTIFICATEUR TOK-VIRGULE
                    EXPRESSION.1 TOK-VIRGULE EXPRESSION.2)
  (DECLARE (IGNORE TOK-CHARGER TOK-VIRGULE TOK-VIRGULE))
  (LIST :CHARGER IDENTIFICATEUR EXPRESSION.1 EXPRESSION.2))

(DEFUN CHARGER11 (CHARGER/1 TOK-VIRGULE IDENTIFICATEUR)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC CHARGER/1 IDENTIFICATEUR))

(DEFUN GARER11 (TOK-GARER IDENTIFICATEUR TOK-VIRGULE EXPRESSION.1
                TOK-VIRGULE EXPRESSION.2)
  (DECLARE (IGNORE TOK-GARER TOK-VIRGULE TOK-VIRGULE))
  (LIST :GARER IDENTIFICATEUR EXPRESSION.1 EXPRESSION.2))

(DEFUN APPEL/111 (IDENTIFICATEUR TOK-PARGAUCHE)
  (DECLARE (IGNORE TOK-PARGAUCHE))
  (LIST :APPEL IDENTIFICATEUR))

(DEFUN APPEL11 (APPEL/1 LISTE-EXPRESSION TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARDROITE))
  (NCONC APPEL/1 LISTE-EXPRESSION))

(DEFUN APPEL12 (APPEL/1 TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARDROITE))
  (PROGN APPEL/1))

(DEFUN RESULTAT12 (TOK-RESULTAT EXPRESSION)
  (DECLARE (IGNORE TOK-RESULTAT))
  (LIST :RESULTAT EXPRESSION))

(DEFUN RETOUR12 (TOK-RETOUR)
  (DECLARE (IGNORE TOK-RETOUR))
  (LIST :RETOUR))

(DEFUN RETOUR13 (TOK-RETOUR TOK-EN EXPRESSION)
  (DECLARE (IGNORE TOK-RETOUR TOK-EN))
  (LIST :RETOUR-EN EXPRESSION))

(DEFUN FAIRE-POUR13 (TOK-FAIRE TOK-NUMERO TOK-POUR IDENTIFICATEUR
                     TOK-FLECHE EXPRESSION)
  (DECLARE (IGNORE TOK-FAIRE TOK-POUR TOK-FLECHE))
  (LIST TOK-NUMERO IDENTIFICATEUR EXPRESSION))

(DEFUN FAIRE-POUR-PAS13 (FAIRE-POUR TOK-PAS EXPRESSION)
  (DECLARE (IGNORE TOK-PAS))
  (SNOC FAIRE-POUR EXPRESSION))

(DEFUN FAIRE-POUR-PAS14 (FAIRE-POUR) (SNOC FAIRE-POUR NIL))

(DEFUN FAIRE-TANT-QUE14 (FAIRE-POUR-PAS TOK-TANT TOK-QUE DISJONCTION)
  (DECLARE (IGNORE TOK-TANT TOK-QUE))
  (CONS :FAIRE-TANT-QUE (SNOC FAIRE-POUR-PAS DISJONCTION)))

(DEFUN FAIRE-JUSQU-A14 (FAIRE-POUR-PAS TOK-JUSQUA EXPRESSION)
  (DECLARE (IGNORE TOK-JUSQUA))
  (CONS :FAIRE-JUSQU-A (SNOC FAIRE-POUR-PAS EXPRESSION)))

(DEFUN DEBUT-FIN14 (TOK-DEBUT LISTE-INST-OU-DECL TOK-FIN)
  (DECLARE (IGNORE TOK-DEBUT TOK-FIN))
  (CONS :DEBUT LISTE-INST-OU-DECL))

(DEFUN PAUSE14 (TOK-PAUSE) (DECLARE (IGNORE TOK-PAUSE)) (LIST :PAUSE))

(DEFUN TERMINER14 (TOK-TERMINER)
  (DECLARE (IGNORE TOK-TERMINER))
  (LIST :TERMINER))

(DEFUN SI-ALORS14 (TOK-SI DISJONCTION TOK-ALORS INSTRUCTION)
  (DECLARE (IGNORE TOK-SI TOK-ALORS))
  (LIST :SI DISJONCTION INSTRUCTION))

(DEFUN SI-ALORS-SINON14 (SI-ALORS TOK-SINON INSTRUCTION)
  (DECLARE (IGNORE TOK-SINON))
  (SNOC SI-ALORS INSTRUCTION))

(DEFUN ALLER-EN14 (TOK-ALLER TOK-EN EXPRESSION)
  (DECLARE (IGNORE TOK-ALLER TOK-EN))
  (LIST :ALLER-EN EXPRESSION))

(DEFUN SPEC-REP14 (TOK-FOIS)
  (DECLARE (IGNORE TOK-FOIS))
  (LIST :REP-VAR))

(DEFUN SPEC-REP-NUM14 (TOK-NUMERO) (LIST :REP TOK-NUMERO))

(DEFUN SPECIFICATION14 (TOK-LITCHAINE)
  (LIST :SPEC-CHAINE '(:REP-1) TOK-LITCHAINE))

(DEFUN SPECIFICATION15 (TOK-DIVISE)
  (DECLARE (IGNORE TOK-DIVISE))
  (LIST :SPEC-SLASH '(:REP-1)))

(DEFUN SPECIFICATION16 (TOK-X)
  (DECLARE (IGNORE TOK-X))
  (LIST :SPEC-SPACE '(:REP-1)))

(DEFUN SPECIFICATION17 (TOK-C)
  (DECLARE (IGNORE TOK-C))
  (LIST :SPEC-CR '(:REP-1)))

(DEFUN SPECIFICATION18 (TOK-L)
  (DECLARE (IGNORE TOK-L))
  (LIST :SPEC-NL '(:REP-1)))

(DEFUN SPECIFICATION19 (TOK-U)
  (DECLARE (IGNORE TOK-U))
  (LIST :SPEC-U '(:REP-1)))

(DEFUN SPECIFICATION20 (TOK-F TOK-NUMERO.1 TOK-POINT TOK-NUMERO.2)
  (DECLARE (IGNORE TOK-F TOK-POINT))
  (LIST :SPEC-F '(:REP-1) TOK-NUMERO.1 TOK-NUMERO.2))

(DEFUN SPECIFICATION21 (TOK-E TOK-NUMERO.1 TOK-POINT TOK-NUMERO.2)
  (DECLARE (IGNORE TOK-E TOK-POINT))
  (LIST :SPEC-E '(:REP-1) TOK-NUMERO.1 TOK-NUMERO.2))

(DEFUN SPECIFICATION22 (SPEC-REP TOK-LITCHAINE)
  (LIST :SPEC-CHAINE SPEC-REP TOK-LITCHAINE))

(DEFUN SPECIFICATION23 (SPEC-REP TOK-DIVISE)
  (DECLARE (IGNORE TOK-DIVISE))
  (LIST :SPEC-SLASH SPEC-REP))

(DEFUN SPECIFICATION24 (SPEC-REP TOK-X)
  (DECLARE (IGNORE TOK-X))
  (LIST :SPEC-SPACE SPEC-REP))

(DEFUN SPECIFICATION25 (SPEC-REP TOK-C)
  (DECLARE (IGNORE TOK-C))
  (LIST :SPEC-CR SPEC-REP))

(DEFUN SPECIFICATION26 (SPEC-REP TOK-L)
  (DECLARE (IGNORE TOK-L))
  (LIST :SPEC-NL SPEC-REP))

(DEFUN SPECIFICATION27 (SPEC-REP-NUM TOK-U)
  (DECLARE (IGNORE TOK-U))
  (LIST :SPEC-U SPEC-REP-NUM))

(DEFUN SPECIFICATION28 (SPEC-REP-NUM TOK-F TOK-NUMERO.1 TOK-POINT
                        TOK-NUMERO.2)
  (DECLARE (IGNORE TOK-F TOK-POINT))
  (LIST :SPEC-F SPEC-REP-NUM TOK-NUMERO.1 TOK-NUMERO.2))

(DEFUN SPECIFICATION29 (SPEC-REP-NUM TOK-E TOK-NUMERO.1 TOK-POINT
                        TOK-NUMERO.2)
  (DECLARE (IGNORE TOK-E TOK-POINT))
  (LIST :SPEC-E SPEC-REP-NUM TOK-NUMERO.1 TOK-NUMERO.2))

(DEFUN LISTE-SPEC29 (LISTE-SPEC TOK-VIRGULE SPECIFICATION)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC LISTE-SPEC SPECIFICATION))

(DEFUN LISTE-SPEC30 (SPECIFICATION) (LIST SPECIFICATION))

(DEFUN FORMAT30 (TOK-CROGAUCHE LISTE-SPEC TOK-CRODROITE)
  (DECLARE (IGNORE TOK-CROGAUCHE TOK-CRODROITE))
  (PROGN LISTE-SPEC))

(DEFUN AFFICHER/FORMAT30 (TOK-AFFICHER FORMAT)
  (DECLARE (IGNORE TOK-AFFICHER))
  (LIST :AFFICHER FORMAT))

(DEFUN AFFICHER30 (TOK-AFFICHER LISTE-EXPRESSION)
  (DECLARE (IGNORE TOK-AFFICHER))
  (LIST* :AFFICHER NIL LISTE-EXPRESSION))

(DEFUN AFFICHER31 (AFFICHER/FORMAT LISTE-EXPRESSION)
  (NCONC AFFICHER/FORMAT LISTE-EXPRESSION))

(DEFUN LIRE31 (TOK-LIRE LISTE-REFERENCE)
  (DECLARE (IGNORE TOK-LIRE))
  (CONS :LIRE LISTE-REFERENCE))

(DEFUN AFFECTATION31 (REFERENCE TOK-FLECHE EXPRESSION)
  (DECLARE (IGNORE TOK-FLECHE))
  (LIST :AFFECTATION REFERENCE EXPRESSION))

(DEFUN LISTE-REFERENCE31 (LISTE-REFERENCE TOK-VIRGULE REFERENCE)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC LISTE-REFERENCE REFERENCE))

(DEFUN LISTE-REFERENCE32 (REFERENCE) (LIST REFERENCE))

(DEFUN REFERENCE/VECTEUR32 (IDENTIFICATEUR TOK-CROGAUCHE EXPRESSION)
  (DECLARE (IGNORE TOK-CROGAUCHE))
  (LIST :AREF IDENTIFICATEUR EXPRESSION))

(DEFUN REFERENCE32 (REFERENCE/VECTEUR TOK-VIRGULE EXPRESSION
                    TOK-CRODROITE)
  (DECLARE (IGNORE TOK-VIRGULE TOK-CRODROITE))
  (SNOC REFERENCE/VECTEUR EXPRESSION))

(DEFUN REFERENCE33 (REFERENCE/VECTEUR TOK-CRODROITE)
  (DECLARE (IGNORE TOK-CRODROITE))
  (PROGN REFERENCE/VECTEUR))

(DEFUN REFERENCE34 (IDENTIFICATEUR) (LIST :VREF IDENTIFICATEUR))

(DEFUN DECL-LOCAL34 (TOK-LOCAL LISTE-IDENTIFICATEUR)
  (DECLARE (IGNORE TOK-LOCAL))
  (PROGN LISTE-IDENTIFICATEUR))

(DEFUN DECL-PROCEDURE/TETE34 (TOK-PROCEDURE
                              IDENTIFICATEUR
                              TOK-PARGAUCHE)
  (DECLARE (IGNORE TOK-PROCEDURE TOK-PARGAUCHE))
  (LIST :PROCEDURE IDENTIFICATEUR))

(DEFUN DECL-PROCEDURE/N34 (DECL-PROCEDURE/TETE LISTE-IDENTIFICATEUR
                           TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARDROITE))
  (SNOC DECL-PROCEDURE/TETE LISTE-IDENTIFICATEUR))

(DEFUN DECL-PROCEDURE/034 (DECL-PROCEDURE/TETE TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARDROITE))
  (SNOC DECL-PROCEDURE/TETE NIL))

(DEFUN DECL-PROCEDURE34 (DECL-PROCEDURE/0)
  (SNOC DECL-PROCEDURE/0 NIL))

(DEFUN DECL-PROCEDURE35 (DECL-PROCEDURE/0 DECL-LOCAL)
  (SNOC DECL-PROCEDURE/0 DECL-LOCAL))

(DEFUN DECL-PROCEDURE36 (DECL-PROCEDURE/N)
  (SNOC DECL-PROCEDURE/N NIL))

(DEFUN DECL-PROCEDURE37 (DECL-PROCEDURE/N DECL-LOCAL)
  (SNOC DECL-PROCEDURE/N DECL-LOCAL))

(DEFUN DECL-TABL/137 (IDENTIFICATEUR TOK-CROGAUCHE EXPRESSION)
  (DECLARE (IGNORE TOK-CROGAUCHE))
  (LIST :ADECL IDENTIFICATEUR EXPRESSION))

(DEFUN DECL-TABL37 (DECL-TABL/1 TOK-VIRGULE EXPRESSION TOK-CRODROITE)
  (DECLARE (IGNORE TOK-VIRGULE TOK-CRODROITE))
  (SNOC DECL-TABL/1 EXPRESSION))

(DEFUN DECL-TABL38 (DECL-TABL/1 TOK-CRODROITE)
  (DECLARE (IGNORE TOK-CRODROITE))
  (PROGN DECL-TABL/1))

(DEFUN LISTE-DECL-TABL38 (LISTE-DECL-TABL TOK-VIRGULE DECL-TABL)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC LISTE-DECL-TABL DECL-TABL))

(DEFUN LISTE-DECL-TABL39 (DECL-TABL) (LIST DECL-TABL))

(DEFUN DECL-TABLEAU39 (TOK-TABLEAU LISTE-DECL-TABL)
  (DECLARE (IGNORE TOK-TABLEAU))
  (CONS :TABLEAU LISTE-DECL-TABL))

(DEFUN DECL-CHAINE39 (TOK-CHAINE LISTE-IDENTIFICATEUR)
  (DECLARE (IGNORE TOK-CHAINE))
  (CONS :CHAINE LISTE-IDENTIFICATEUR))

(DEFUN LIBERATION39 (TOK-LIBERER LISTE-IDENTIFICATEUR)
  (DECLARE (IGNORE TOK-LIBERER))
  (CONS :LIBERER LISTE-IDENTIFICATEUR))

(DEFUN LISTE-INSTRUCTION39 (LISTE-INSTRUCTION TOK-PTVIRG INSTRUCTION)
  (DECLARE (IGNORE TOK-PTVIRG))
  (SNOC LISTE-INSTRUCTION INSTRUCTION))

(DEFUN LISTE-INSTRUCTION40 (INSTRUCTION TOK-PTVIRG TOK-COMMENTAIRE)
  (DECLARE (IGNORE TOK-PTVIRG))
  (LIST INSTRUCTION (LIST :COMMENTAIRE TOK-COMMENTAIRE)))

(DEFUN LISTE-INSTRUCTION41 (INSTRUCTION) (LIST INSTRUCTION))

(DEFUN LISTE-INST-OU-DECL41 (LISTE-INST-OU-DECL TOK-PTVIRG
                             INSTRUCTION)
  (DECLARE (IGNORE TOK-PTVIRG))
  (SNOC LISTE-INST-OU-DECL INSTRUCTION))

(DEFUN LISTE-INST-OU-DECL42 (LISTE-INST-OU-DECL TOK-PTVIRG DECL)
  (DECLARE (IGNORE TOK-PTVIRG))
  (SNOC LISTE-INST-OU-DECL DECL))

(DEFUN LISTE-INST-OU-DECL43 (INSTRUCTION) (LIST INSTRUCTION))

(DEFUN LISTE-INST-OU-DECL44 (DECL) (LIST DECL))

(DEFUN LISTE-INST-OU-DECL45 (TOK-COMMENTAIRE)
  (LIST :COMMENTAIRE TOK-COMMENTAIRE))

(DEFUN LIGNE-DECL-PROCEDURE/045 (TOK-NUMERO DECL-PROCEDURE)
  (LIST :LIGNE-PROGRAMME
        TOK-NUMERO
        (LIST :DECL-PROCEDURE DECL-PROCEDURE)))

(DEFUN LIGNE-PROGRAMME45 (TOK-NUMERO LISTE-INST-OU-DECL)
  (LIST* :LIGNE-PROGRAMME TOK-NUMERO LISTE-INST-OU-DECL))

(DEFUN LIGNE-PROGRAMME46 (TOK-NUMERO TOK-COMMENTAIRE)
  (LIST :LIGNE-PROGRAMME
        TOK-NUMERO
        (LIST :COMMENTAIRE TOK-COMMENTAIRE)))

(DEFUN LIGNE-PROGRAMME47 (LIGNE-DECL-PROCEDURE/0 TOK-PTVIRG
                          LISTE-INST-OU-DECL)
  (DECLARE (IGNORE TOK-PTVIRG))
  (NCONC LIGNE-DECL-PROCEDURE/0 LISTE-INST-OU-DECL))

(DEFUN CONDITION47 (TOK-NON CONDITION)
  (DECLARE (IGNORE TOK-NON))
  (LIST :NON CONDITION))

(DEFUN CONDITION48 (TOK-PARGAUCHE DISJONCTION TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARGAUCHE TOK-PARDROITE))
  (PROGN DISJONCTION))

(DEFUN CONDITION49 (EXPRESSION.1 TOK-LT EXPRESSION.2)
  (DECLARE (IGNORE TOK-LT))
  (LIST :LT EXPRESSION.1 EXPRESSION.2))

(DEFUN CONDITION50 (EXPRESSION.1 TOK-LE EXPRESSION.2)
  (DECLARE (IGNORE TOK-LE))
  (LIST :LE EXPRESSION.1 EXPRESSION.2))

(DEFUN CONDITION51 (EXPRESSION.1 TOK-NE EXPRESSION.2)
  (DECLARE (IGNORE TOK-NE))
  (LIST :NE EXPRESSION.1 EXPRESSION.2))

(DEFUN CONDITION52 (EXPRESSION.1 TOK-EQ EXPRESSION.2)
  (DECLARE (IGNORE TOK-EQ))
  (LIST :EG EXPRESSION.1 EXPRESSION.2))

(DEFUN CONDITION53 (EXPRESSION.1 TOK-GT EXPRESSION.2)
  (DECLARE (IGNORE TOK-GT))
  (LIST :GT EXPRESSION.1 EXPRESSION.2))

(DEFUN CONDITION54 (EXPRESSION.1 TOK-GE EXPRESSION.2)
  (DECLARE (IGNORE TOK-GE))
  (LIST :GE EXPRESSION.1 EXPRESSION.2))

(DEFUN CONJONCTION54 (CONJONCTION TOK-ET CONDITION)
  (DECLARE (IGNORE TOK-ET))
  (LIST :ET CONJONCTION CONDITION))

(DEFUN CONJONCTION55 (CONDITION) (PROGN CONDITION))

(DEFUN DISJONCTION55 (DISJONCTION TOK-OU CONJONCTION)
  (DECLARE (IGNORE TOK-OU))
  (LIST :OU DISJONCTION CONJONCTION))

(DEFUN DISJONCTION56 (CONJONCTION) (PROGN CONJONCTION))

(DEFUN LISTE-IDENTIFICATEUR56 (LISTE-IDENTIFICATEUR
                               TOK-VIRGULE
                               IDENTIFICATEUR)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC LISTE-IDENTIFICATEUR IDENTIFICATEUR))

(DEFUN LISTE-IDENTIFICATEUR57 (IDENTIFICATEUR) (LIST IDENTIFICATEUR))

(DEFUN LISTE-EXPRESSION57 (LISTE-EXPRESSION TOK-VIRGULE EXPRESSION)
  (DECLARE (IGNORE TOK-VIRGULE))
  (SNOC LISTE-EXPRESSION EXPRESSION))

(DEFUN LISTE-EXPRESSION58 (EXPRESSION) (LIST EXPRESSION))

(DEFUN SIMPLE58 (TOK-SI DISJONCTION TOK-ALORS EXPRESSION.1 TOK-SINON
                 EXPRESSION.2)
  (DECLARE (IGNORE TOK-SI TOK-ALORS TOK-SINON))
  (LIST :XI DISJONCTION EXPRESSION.1 EXPRESSION.2))

(DEFUN SIMPLE59 (IDENTIFICATEUR TOK-PARGAUCHE TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARGAUCHE TOK-PARDROITE))
  (LIST :FONCTION IDENTIFICATEUR))

(DEFUN SIMPLE60 (IDENTIFICATEUR TOK-PARGAUCHE LISTE-EXPRESSION
                 TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARGAUCHE TOK-PARDROITE))
  (LIST* :FONCTION IDENTIFICATEUR LISTE-EXPRESSION))

(DEFUN SIMPLE61 (TOK-LITCHAINE) (PROGN TOK-LITCHAINE))

(DEFUN SIMPLE62 (TOK-PARGAUCHE EXPRESSION TOK-PARDROITE)
  (DECLARE (IGNORE TOK-PARGAUCHE TOK-PARDROITE))
  (PROGN EXPRESSION))

(DEFUN SIMPLE63 (TOK-NOMBRE) (PROGN TOK-NOMBRE))

(DEFUN SIMPLE64 (TOK-NUMERO) (PROGN TOK-NUMERO))

(DEFUN FACTEUR64 (FACTEUR TOK-PUISSANCE SIMPLE)
  (DECLARE (IGNORE TOK-PUISSANCE))
  (LIST :PUISSANCE FACTEUR SIMPLE))

(DEFUN TERME64 (TERME TOK-FOIS FACTEUR)
  (DECLARE (IGNORE TOK-FOIS))
  (LIST :FOIS TERME FACTEUR))

(DEFUN TERME65 (TERME TOK-DIVISE FACTEUR)
  (DECLARE (IGNORE TOK-DIVISE))
  (LIST :DIVISE TERME FACTEUR))

(DEFUN EXPRESSION65 (TOK-MOINS TERME)
  (DECLARE (IGNORE TOK-MOINS))
  (LIST :NEG TERME))

(DEFUN EXPRESSION66 (EXPRESSION TOK-MOINS TERME)
  (DECLARE (IGNORE TOK-MOINS))
  (LIST :MOINS EXPRESSION TERME))

(DEFUN EXPRESSION67 (EXPRESSION TOK-PLUS TERME)
  (DECLARE (IGNORE TOK-PLUS))
  (LIST :PLUS EXPRESSION TERME))

(DEFUN EXPRESSION68 (EXPRESSION TOK-CONCAT TERME)
  (DECLARE (IGNORE TOK-CONCAT))
  (LIST :CONCAT EXPRESSION TERME))

(DEFUN IDENTIFICATEUR68 (TOK-IDENTIFICATEUR)
  (PROGN TOK-IDENTIFICATEUR))

(DEFUN AFFIC/FORMAT68 (TOK-AFFIC FORMAT)
  (DECLARE (IGNORE TOK-AFFIC))
  (LIST :AFFICHER FORMAT))

(DEFUN AFFIC68 (AFFIC/FORMAT LISTE-EXPRESSION)
  (NCONC AFFIC/FORMAT LISTE-EXPRESSION))

(DEFUN AFFIC69 (TOK-AFFIC LISTE-EXPRESSION)
  (DECLARE (IGNORE TOK-AFFIC))
  (LIST* :AFFICHER NIL LISTE-EXPRESSION))

(DEFUN START69 (LISTE-INSTRUCTION)
  (CONS :LISTE-INSTRUCTION LISTE-INSTRUCTION))

(DEFUN START70 (AFFIC) (LIST :LISTE-INSTRUCTION AFFIC))

(DEFUN START71 (TOK-ERREUR) (PROGN TOK-ERREUR))

(DEFUN START72 () (PROGN NIL))


(EVAL-WHEN (:COMPILE-TOPLEVEL)
  (UNLESS (MEMBER "zebu-regex" *MODULES* :TEST #'EQUAL)
    (WARN "Load the Zebu Compiler!")))
(DECLAIM (SPECIAL ZEBU::*REGEX-GROUPS* ZEBU::*REGEX-GROUPINGS*))
(DEFUN TOK-AFFICHER (STRING &OPTIONAL (ZEBU::START 0)
                     (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "AFFICHER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-ALLER (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "ALLER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-ALORS (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "ALORS"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-CHAINE (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 6)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "CHAINE"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 6)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-CHARGER (STRING &OPTIONAL (ZEBU::START 0)
                    (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 7)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "CHARGER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 7)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-DEBUT (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "DEBUT"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-EN (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 2)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "EN"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 2)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-ET (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 2)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "ET"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 2)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-EXECUTER (STRING &OPTIONAL (ZEBU::START 0)
                     (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "EXECUTER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-FIN (STRING &OPTIONAL (ZEBU::START 0)
                (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 3)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "FIN"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 3)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-FAIRE (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "FAIRE"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-GARER (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "GARER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-JUSQUA (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 6)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "JUSQUA"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 6)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-LIBERER (STRING &OPTIONAL (ZEBU::START 0)
                    (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 7)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "LIBERER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 7)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-LIRE (STRING &OPTIONAL (ZEBU::START 0)
                 (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 4)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "LIRE"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 4)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-LOCAL (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "LOCAL"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-NON (STRING &OPTIONAL (ZEBU::START 0)
                (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 3)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "NON"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 3)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-OU (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 2)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "OU"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 2)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PAS (STRING &OPTIONAL (ZEBU::START 0)
                (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 3)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "PAS"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 3)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PAUSE (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "PAUSE"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-POUR (STRING &OPTIONAL (ZEBU::START 0)
                 (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 4)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "POUR"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 4)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PROCEDURE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 9)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "PROCEDURE"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 9)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-QUE (STRING &OPTIONAL (ZEBU::START 0)
                (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 3)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "QUE"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 3)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-RESULTAT (STRING &OPTIONAL (ZEBU::START 0)
                     (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "RESULTAT"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-RETOUR (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 6)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "RETOUR"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 6)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-SI (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 2)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "SI"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 2)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-SINON (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 5)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "SINON"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 5)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-SUPPRIMER (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 9)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "SUPPRIMER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 9)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-TABLEAU (STRING &OPTIONAL (ZEBU::START 0)
                    (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 7)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "TABLEAU"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 7)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-TANT (STRING &OPTIONAL (ZEBU::START 0)
                 (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 4)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "TANT"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 4)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-TERMINER (STRING &OPTIONAL (ZEBU::START 0)
                     (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "TERMINER"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-X (STRING &OPTIONAL (ZEBU::START 0)
              (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\X))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-C (STRING &OPTIONAL (ZEBU::START 0)
              (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\C))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-L (STRING &OPTIONAL (ZEBU::START 0)
              (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\L))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-F (STRING &OPTIONAL (ZEBU::START 0)
              (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\F))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-E (STRING &OPTIONAL (ZEBU::START 0)
              (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\E))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-U (STRING &OPTIONAL (ZEBU::START 0)
              (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\U))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-GT (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\>))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-GE (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 2)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    ">="
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 2)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-LT (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\<))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-LE (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 2)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "<="
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 2)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-NE (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\#))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-EQ (STRING &OPTIONAL (ZEBU::START 0)
               (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\=))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-AFFIC (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\?))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PLUS (STRING &OPTIONAL (ZEBU::START 0)
                 (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\+))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-MOINS (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\-))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-CONCAT (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\!))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-FOIS (STRING &OPTIONAL (ZEBU::START 0)
                 (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\*))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-DIVISE (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\/))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PUISSANCE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\^))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-VIRGULE (STRING &OPTIONAL (ZEBU::START 0)
                    (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\,))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-POINT (STRING &OPTIONAL (ZEBU::START 0)
                  (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\.))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PARGAUCHE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\())
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PARDROITE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\)))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-CROGAUCHE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\[))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-CRODROITE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\]))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-FLECHE (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\_))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-PTVIRG (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (IF (AND (< ZEBU::INDEX LENGTH)
                              (EQL (CHAR STRING ZEBU::INDEX) #\;))
                         (INCF ZEBU::INDEX)
                         (RETURN-FROM ZEBU::COMPARE NIL))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-NUMERO (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "{NUMERO}"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-NOMBRE (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "{NOMBRE}"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-LITCHAINE (STRING &OPTIONAL (ZEBU::START 0)
                      (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "{CHAINE}"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-IDENTIFICATEUR (STRING &OPTIONAL (ZEBU::START 0)
                           (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 16)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "{IDENTIFICATEUR}"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 16)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-COMMENTAIRE (STRING &OPTIONAL (ZEBU::START 0)
                        (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 13)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "{COMMENTAIRE}"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 13)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))

(DEFUN TOK-ERREUR (STRING &OPTIONAL (ZEBU::START 0)
                   (ZEBU::END (LENGTH STRING)))
  (WHEN (PROGN (SETF ZEBU::*REGEX-GROUPINGS* 1)
               (BLOCK ZEBU::FINAL-RETURN
                 (BLOCK ZEBU::COMPARE
                   (LET ((ZEBU::INDEX ZEBU::START)
                         (LENGTH ZEBU::END))
                     (SETF (SVREF ZEBU::*REGEX-GROUPS* 0)
                           (LIST ZEBU::INDEX NIL))
                     (LET ((ZEBU::NEW-INDEX (+ ZEBU::INDEX 8)))
                       (IF (< LENGTH ZEBU::NEW-INDEX)
                           (RETURN-FROM ZEBU::COMPARE NIL))
                       (IF (STRING= STRING
                                    "{ERREUR}"
                                    :START1
                                    ZEBU::INDEX
                                    :END1
                                    ZEBU::NEW-INDEX)
                           (INCF ZEBU::INDEX 8)
                           (RETURN-FROM ZEBU::COMPARE NIL)))
                     (SETF (CADR (SVREF ZEBU::*REGEX-GROUPS* 0))
                           ZEBU::INDEX)
                     (RETURN-FROM ZEBU::FINAL-RETURN T)))))
    (SECOND (SVREF ZEBU::*REGEX-GROUPS* 0))))
